-- Migration: Consent-First Pipeline
-- Adds follow-up outreach columns and indexes for the new pipeline where:
--   1. Initial outreach uses license data only (no enrichment)
--   2. Research/enrichment runs ONLY after prospect visits /join (interaction_stage='interested')
--   3. Enriched follow-up email is generated post-research
--   4. Referral network consent is captured separately from TCPA consent
--
-- Run this in Supabase SQL Editor (Legacy Financial project: kxmojndpgxgbykxjtxba)

-- ═══════════════════════════════════════════
-- 1. Follow-up outreach columns (enriched, post-interest)
-- ═══════════════════════════════════════════
ALTER TABLE recruitment_prospects
  ADD COLUMN IF NOT EXISTS followup_email_subject TEXT,
  ADD COLUMN IF NOT EXISTS followup_email_body TEXT,
  ADD COLUMN IF NOT EXISTS followup_call_opener TEXT,
  ADD COLUMN IF NOT EXISTS followup_call_voicemail TEXT,
  ADD COLUMN IF NOT EXISTS followup_processed_at TIMESTAMPTZ;

COMMENT ON COLUMN recruitment_prospects.followup_email_subject IS 'Subject for enriched follow-up email (post-interest, uses web_presence data)';
COMMENT ON COLUMN recruitment_prospects.followup_email_body IS 'Body for enriched follow-up email (4 paragraphs, personalized from research)';
COMMENT ON COLUMN recruitment_prospects.followup_call_opener IS 'Call script opener for enriched follow-up (uses research findings)';
COMMENT ON COLUMN recruitment_prospects.followup_call_voicemail IS 'Voicemail script for enriched follow-up';
COMMENT ON COLUMN recruitment_prospects.followup_processed_at IS 'When the enriched follow-up was generated by AI';

-- ═══════════════════════════════════════════
-- 2. Index for follow-up outreach worker queries
-- ═══════════════════════════════════════════

-- The follow-up worker fetches: interaction_stage='interested' AND research_status='scored' AND followup_email_body IS NULL
CREATE INDEX IF NOT EXISTS idx_prospects_followup_ready
  ON recruitment_prospects (interaction_stage, research_status)
  WHERE interaction_stage = 'interested'
    AND research_status = 'scored'
    AND followup_email_body IS NULL;

-- Composite index for the consent-gated researcher query:
-- research_status='unscored' AND interaction_stage='interested'
CREATE INDEX IF NOT EXISTS idx_prospects_interested_unscored
  ON recruitment_prospects (last_interaction_at DESC NULLS LAST)
  WHERE research_status = 'unscored'
    AND interaction_stage = 'interested';

-- ═══════════════════════════════════════════
-- 3. Index for referral consent lookups
-- ═══════════════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_prospects_referral_consent
  ON recruitment_prospects ((properties->>'referral_consent'))
  WHERE (properties->>'referral_consent') = 'true';
